[build]
  functions = "netlify-functions"  # Directory where your serverless functions reside
  command = "npm run build"        # Command to build the React app

[build.environment]
  PYTHON_VERSION = "3.9"           # Specify the Python version for serverless functions

[context.production.environment]
  FLASK_ENV = "production"         # Flask environment configuration (if needed)
